version: '3'
services:
  data_broker:
    image: ghcr.io/eclipse/kuksa.val/databroker:master
    hostname: "data_broker"
    command: --insecure --metadata /val.json --address 0.0.0.0 --port 55555
    volumes:
      - ./assets/tele-op-vss-model.json:/val.json 
    ports:
      - 55555:55555
    networks:
      - ros2
  simulator:
    build:
      context: .
    hostname: simulator
    environment:
      - width=1900
      - height=1080
      - x_coord=1
      - y_coord=1
      - angle=2
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/workspace:cached
    networks:
      - ros2
networks:
  ros2:
    name: ros2 
